In [ ]:
# import python library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Load Dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/Titanic.csv')

In [ ]:
y = df['Survived']

In [ ]:
X = df.drop(['PassengerId','Name','Ticket','Cabin','Embarked'],axis=1)
X

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [ ]:
X['Age'].median()

28.0

In [ ]:
X['Age']= X['Age'].fillna(X['Age'].median())

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.9+ KB


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X['Sex']= le.fit_transform(X['Sex'])
X

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    1  22.0      1      0   7.2500
1           1       1    0  38.0      1      0  71.2833
2           1       3    0  26.0      0      0   7.9250
3           1       1    0  35.0      1      0  53.1000
4           0       3    1  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
886         0       2    1  27.0      0      0  13.0000
887         1       1    0  19.0      0      0  30.0000
888         0       3    0  28.0      1      2  23.4500
889         1       1    1  26.0      0      0  30.0000
890         0       3    1  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
X=X.drop(['Survived'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Ref Link: https://www.kaggle.com/code/faressayah/support-vector-machine-pca-tutorial-for-beginner

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

Ref Link: https://www.kaggle.com/code/tflare/testing-multiple-models-with-scikit-learn-0-79425

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

models = []
models.append(("LogisticRegression",LogisticRegression()))
models.append(("SVC",SVC()))
models.append(("LinearSVC",LinearSVC()))
models.append(("KNeighbors",KNeighborsClassifier()))
models.append(("DecisionTree",DecisionTreeClassifier()))
models.append(("RandomForest",RandomForestClassifier()))
rf2 = RandomForestClassifier(n_estimators=100, criterion='gini',
                                max_depth=10, random_state=0, max_features=None)
models.append(("RandomForest2",rf2))
models.append(("MLPClassifier",MLPClassifier(solver='lbfgs', random_state=0)))


results = []
for name,model in models:
    print(f"Evaluating {name}")
    model.fit(X_train, y_train)
    result = print_score(model, X_train, y_train, X_test, y_test, train=True)
    result = print_score(model, X_train, y_train, X_test, y_test, train=False)
    results.append(result)
    print("\n")

Evaluating LogisticRegression
Train Result:
Accuracy Score: 80.20%
_______________________________________________
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    0.818947    0.767932  0.801966    0.793440      0.799745
recall       0.876126    0.679104  0.801966    0.777615      0.801966
f1-score     0.846572    0.720792  0.801966    0.783682      0.799228
support    444.000000  268.000000  0.801966  712.000000    712.000000
_______________________________________________
Confusion Matrix: 
 [[389  55]
 [ 86 182]]

Test Result:
Accuracy Score: 81.01%
_______________________________________________
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.814159   0.803030  0.810056    0.808595      0.809558
recall       0.876190   0.716216  0.810056    0.796203      0.810056
f1-score     0.844037   0.757143  0.810056    0.800590      0.808114
support    105.000000  74.000000  0.8

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Confusion Matrix: 
 [[104   1]
 [ 63  11]]



Evaluating KNeighbors
Train Result:
Accuracy Score: 79.63%
_______________________________________________
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    0.818763    0.753086  0.796348    0.785925      0.794042
recall       0.864865    0.682836  0.796348    0.773850      0.796348
f1-score     0.841183    0.716243  0.796348    0.778713      0.794155
support    444.000000  268.000000  0.796348  712.000000    712.000000
_______________________________________________
Confusion Matrix: 
 [[384  60]
 [ 85 183]]

Test Result:
Accuracy Score: 68.72%
_______________________________________________
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.705882   0.650000  0.687151    0.677941      0.682780
recall       0.800000   0.527027  0.687151    0.663514      0.687151
f1-score     0.750000   0.582090  0.687151    0.666045      0.680585

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [ ]:
# import pandas as pd
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC, LinearSVC
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.naive_bayes import GaussianNB
# from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# def print_score(clf, X_train, y_train, X_test, y_test, train=True):
#     if train:
#         pred = clf.predict(X_train)
#         clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True)).transpose()
#         print("Train Result:\n================================================")
#         print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
#         print("_______________________________________________")
#         print(f"CLASSIFICATION REPORT:\n{clf_report}")
#         print("_______________________________________________")
#         print(f"Confusion Matrix: \n{confusion_matrix(y_train, pred)}\n")

#     else:
#         pred = clf.predict(X_test)
#         clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True)).transpose()
#         print("Test Result:\n================================================")
#         print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
#         print("_______________________________________________")
#         print(f"CLASSIFICATION REPORT:\n{clf_report}")
#         print("_______________________________________________")
#         print(f"Confusion Matrix: \n{confusion_matrix(y_test, pred)}\n")

# # List of models to evaluate
# models = [
#     ("LogisticRegression", LogisticRegression()),
#     ("SVC", SVC()),
#     ("LinearSVC", LinearSVC()),
#     ("KNeighbors", KNeighborsClassifier()),
#     ("DecisionTree", DecisionTreeClassifier()),
#     ("RandomForest", RandomForestClassifier()),
#     ("RandomForest2", RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=10, random_state=0, max_features=None)),
#     ("MLPClassifier", MLPClassifier(solver='lbfgs', random_state=0))
# ]

# results = []

# # Evaluate each model
# for name, model in models:
#     print(f"Evaluating {name}")
#     model.fit(X_train, y_train)
#     print_score(model, X_train, y_train, X_test, y_test, train=True)
#     print_score(model, X_train, y_train, X_test, y_test, train=False)
#     print("\n")